name: Deploy to VK Cloud VM

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Executing remote ssh commands using ssh key
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            echo "--- Начало автоматического деплоя ---"
            cd ~
            echo "Пайплайн успешно отработал. Дата: \$(date)" >> deploy.log
            echo "Последние 3 строки лога деплоя:"
            tail -n 3 deploy.log
            echo "--- Деплой успешно завершен! ---"
